# Generated by Django 6.0.1 on 2026-01-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('land', 'Land Sales'), ('residential', 'Residential Housing'), ('commercial', 'Commercial Housing')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=20)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='properties/')),
                ('is_registered', models.BooleanField(default=False, help_text='Check if Indenture/Title is ready')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon_name', models.CharField(blank=True, help_text='FontAwesome class (e.g. fas fa-home)', max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='services/')),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='EmanHomes', max_length=100)),
                ('main_phone', models.CharField(help_text='The primary number shown in the header', max_length=20)),
                ('main_email', models.EmailField(help_text='The primary email shown in the header', max_length=254)),
                ('office_location', models.CharField(default='East Legon, Accra', max_length=255)),
                ('facebook_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('x_link', models.URLField(blank=True)),
                ('youtube_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
