# Generated by Django 6.0.1 on 2026-01-24 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='x_link',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='youtube_link',
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('land', 'Land Sales'), ('residential', 'Residential Housing'), ('commercial', 'Commercial Construction')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_name',
            field=models.CharField(blank=True, help_text='FontAwesome class', max_length=50),
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Indenture, Site Plan, Receipt', max_length=100)),
                ('document_file', models.FileField(upload_to='client_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
