# Generated by Django 6.0.1 on 2026-01-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_siteconfiguration_linkedin_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g. CEO, Lead Surveyor', max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('bio', models.TextField(blank=True, help_text='Short description of expertise')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers show first')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
