# Generated by Django 6.0.1 on 2026-01-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon_name',
            field=models.CharField(blank=True, help_text='FontAwesome class (e.g. fas fa-home)', max_length=50),
        ),
    ]
