# Generated by Django 5.1.5 on 2026-02-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_service_icon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(default='New Inquiry', max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Site Configuration', 'verbose_name_plural': 'Site Configuration'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={},
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_registered',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='main_email',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='office_location',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='display_order',
        ),
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste YouTube or Instagram link here', null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='address',
            field=models.TextField(default='Dzen-Ayor, East Legon, Accra, Ghana'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email',
            field=models.EmailField(default='emanpages@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='facebook',
            field=models.URLField(blank=True, default='https://www.facebook.com/emanhomes', null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='instagram',
            field=models.URLField(blank=True, default='https://www.instagram.com/emanhomes', null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('land', 'Land'), ('residential', 'Residential House'), ('commercial', 'Commercial Property')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('sold', 'Sold')], default='for_sale', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_name',
            field=models.CharField(help_text='FontAwesome icon class (e.g., fas fa-home)', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='main_phone',
            field=models.CharField(default='+233 20 584 3775', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='EmanHomes', max_length=200),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ClientDocument',
        ),
    ]
